headStartDuration: 30
compassEnabledInNether: true

enableDiscord: false
discordToken: "XXXXX"
ip: "a minecraft server"

discordServerId: "XXXXX"
musicChannelId: "XXXXX"
hunterRoleId: "XXXXX"
runnerRoleId: "XXXXX"
spectatorRoleId: "XXXXX"